/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Isurika
 */
public class ConfirmOrder extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement prestmnt;
    ResultSet Reltset;
    /**
     * Creates new form OrderVerification
     */
    //constructor
    public ConfirmOrder() {
        initComponents();
        this.setLocationRelativeTo(null);//window fit to center
        //database connection
        DbConnector connect = new DbConnector();
        conn = connect.dbConnect();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        imageLog = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnProceedOrder = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        adrs = new javax.swing.JTextArea();
        lblLogImage = new javax.swing.JLabel();
        btnChangeOrder = new javax.swing.JButton();
        btnProceedOrder1 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        imageLog.setBackground(new java.awt.Color(255, 255, 102));
        imageLog.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        imageLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLogMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(420, 537));
        jPanel1.setRequestFocusEnabled(false);

        btnProceedOrder.setBackground(new java.awt.Color(0, 0, 0));
        btnProceedOrder.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnProceedOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnProceedOrder.setText("PLACE ORDER");
        btnProceedOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProceedOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedOrderActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/images/333 (1).png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("DELIVERY ADDRESS");

        adrs.setColumns(20);
        adrs.setRows(5);
        jScrollPane2.setViewportView(adrs);

        lblLogImage.setBackground(new java.awt.Color(255, 255, 102));
        lblLogImage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/images/logImage.png"))); // NOI18N
        lblLogImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblLogImage.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblLogImageAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnChangeOrder.setBackground(new java.awt.Color(0, 0, 0));
        btnChangeOrder.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnChangeOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnChangeOrder.setText("EDIT ORDER");
        btnChangeOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeOrderActionPerformed(evt);
            }
        });

        btnProceedOrder1.setBackground(new java.awt.Color(0, 0, 0));
        btnProceedOrder1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProceedOrder1.setForeground(new java.awt.Color(255, 255, 255));
        btnProceedOrder1.setText("EXIT");
        btnProceedOrder1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProceedOrder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedOrder1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLogImage))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(logo)
                                .addComponent(btnProceedOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnChangeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProceedOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(lblLogImage))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProceedOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnProceedOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProceedOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedOrderActionPerformed
        // confirm order
        String order_status = "draft";
        String address = adrs.getText();

        if(address.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter your recidential address");
        }
        else{
            try {
                JOptionPane.showMessageDialog(null, "Thank you for choosing FAST YUMMY\nYour Order will recieve soon");

                String sql1 = "update ORDERTABLE set ADDRESS = '"+address+"' where ADDRESS = '"+order_status+"'";//insert address to the current order
                prestmnt = conn.prepareStatement(sql1);
                prestmnt.execute();//execute sql1 command
                adrs.setText("");
                this.setVisible(false);
            } 
            catch (SQLException ex) {
                Logger.getLogger(ConfirmOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            
    }//GEN-LAST:event_btnProceedOrderActionPerformed

    private void imageLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLogMouseClicked
       
    }//GEN-LAST:event_imageLogMouseClicked

    private void lblLogImageAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblLogImageAncestorAdded
        FoodOrderingSystem cu = new FoodOrderingSystem();//create new FoodOrderingSystem class object
        Reltset = cu.ShowLogin();//invoke Logout method

        try {
            if (Reltset.next()){
                lblLogImage.setText(Reltset.getString("name")+"  ");
            }
            else{
                lblLogImage.setText("");
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(FoodOrderingSystem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblLogImageAncestorAdded

    private void btnChangeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeOrderActionPerformed
        String order = "draft";
        int dialogButton = JOptionPane.YES_NO_OPTION;//create yes, no dialog buttons
        int answer = JOptionPane.showConfirmDialog(null,"Do you want to change the order?", "Warning",dialogButton);//show confirm-dialog button
        if(answer == JOptionPane.YES_OPTION){
            try {
                String sql1 = "DELETE FROM ORDERTABLE WHERE ADDRESS = '"+order+"'";//delete draft order
                prestmnt = conn.prepareStatement(sql1);
                prestmnt.execute();
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(ConfirmOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnChangeOrderActionPerformed

    private void btnProceedOrder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedOrder1ActionPerformed
        FoodOrderingSystem cu = new FoodOrderingSystem();//create new FoodOrderingSystem class object
        cu.exitAndCancelOrder();
    }//GEN-LAST:event_btnProceedOrder1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderVerification().setVisible(true);
            }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmOrder().setVisible(true);
            }
        });*/
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea adrs;
    private javax.swing.JButton btnChangeOrder;
    private javax.swing.JButton btnProceedOrder;
    private javax.swing.JButton btnProceedOrder1;
    private javax.swing.JLabel imageLog;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblLogImage;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
