/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Isurika
 */
public class WelcomePage extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement prestmnt;
    ResultSet Reltset;

    /**
     *
     */
    public static WelcomePage Instance;
    public JLabel lbl;

    /**
     * Creates new form WelcomePage
     */

    /*FoodOrderingSystem uc = new FoodOrderingSystem();
    uc.checkUser(username, password);*/
    //constructor
    public WelcomePage() {
        initComponents();
        this.setLocationRelativeTo(null);//window fit to center
        //database connection
        DbConnector connect = new DbConnector();
        conn = connect.dbConnect();

        Instance = this;
        lbl = lblLogImage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblLogImage = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(847, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dirty Headline", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("VIEW ITEMS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText(">>");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/images/rere-removebg-preview.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 390, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bringing Food To Your Door");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 480, -1));

        btnExit.setBackground(new java.awt.Color(255, 206, 78));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setText("EXIT");
        btnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 80, 40));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 120, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 485, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/images/333 (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lblLogImage.setBackground(new java.awt.Color(255, 255, 255));
        lblLogImage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogImage.setForeground(new java.awt.Color(0, 0, 0));
        lblLogImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/images/logImage.png"))); // NOI18N
        lblLogImage.setText("SIGN IN / SIGN UP ");
        lblLogImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblLogImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogImage.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblLogImageAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lblLogImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogImageMouseExited(evt);
            }
        });
        jPanel1.add(lblLogImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnLogout.setBackground(new java.awt.Color(255, 206, 78));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 0));
        btnLogout.setText("SIGN OUT");
        btnLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 390, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/images/back.jpg"))); // NOI18N
        jLabel5.setText("icon");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 620));

        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogImageAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblLogImageAncestorAdded
        FoodOrderingSystem cu = new FoodOrderingSystem();//create new FoodOrderingSystem class object
        Reltset = cu.ShowLogin();//invoke Logout method

        try {
            if (Reltset.next()) {
                lblLogImage.setText(Reltset.getString("name") + "  ");
            } else {
                lblLogImage.setText("SIGN IN / SIGN UP ");
            }
        } catch (SQLException ex) {
            Logger.getLogger(FoodOrderingSystem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblLogImageAncestorAdded

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            FoodOrderingSystem cu = new FoodOrderingSystem();//create new FoodOrderingSystem class object
            Reltset = cu.ShowLogin();//invoke ShowLogin method
            if (Reltset.next()) {
                LogOut logout = new LogOut();
                logout.setVisible(true);
            } else {//if no one logged yet
                JOptionPane.showMessageDialog(null, "You have not logged in to the account yet");
            }
        } catch (SQLException ex) {
            Logger.getLogger(WelcomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void lblLogImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogImageMouseClicked
        // show login window
        if ("SIGN IN / SIGN UP ".equals(lblLogImage.getText())) {
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_lblLogImageMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        FoodOrderingSystem cu = new FoodOrderingSystem();//create new FoodOrderingSystem class object
        cu.exitAndCancelOrder();
    }//GEN-LAST:event_btnExitActionPerformed

    private void lblLogImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogImageMouseEntered
        // change color when hoover
        if ("SIGN IN / SIGN UP ".equals(lblLogImage.getText())) {
            lblLogImage.setForeground(Color.blue);
        }
    }//GEN-LAST:event_lblLogImageMouseEntered

    private void lblLogImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogImageMouseExited
        //change color when mouse exited
        if ("SIGN IN / SIGN UP ".equals(lblLogImage.getText())) {
            lblLogImage.setForeground(Color.black);
        }
    }//GEN-LAST:event_lblLogImageMouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        //show the item window
        this.setVisible(false);
        Items item = new Items();
        item.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogImage;
    // End of variables declaration//GEN-END:variables
}
